services:
  postgresql:
    image: postgres:17
    container_name: rlingo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rlingo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5455:5432"
    volumes:
      - rlingo_db_data:/var/lib/postgresql/data

volumes:
  rlingo_db_data:
    driver: local